version: "2"
services:
  nginx:
    image: nginx # ???
  ports:
    - "8080:8080"

  nginx_exporter:
    image: ???
  ports:
    - "8081:8081"

  agent:
    image: grafana/agent:v0.5.0
    volumes:
      - ./agent/config:/etc/agent-config
    entrypoint:
      - /bin/agent
      - -config.file=/etc/agent-config/agent.yaml
    ports:
      - "12345:12345"
