{
 "title": "Agent Info",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "nodename",
    "label": "Instance",
    "query": "label_values(agent_build_info, agent_hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Agent Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Agent Stats",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (agent_hostname, version) (agent_build_info)"
    },
    {
     "expr": "max by (agent_hostname) (time() - process_start_time_seconds{agent_hostname!=\"\"})"
    }
   ]
  },
  { "title": "Prometheus Discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Target Sync",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{agent_hostname=\"$nodename\"}[5m])) by (agent_hostname, scrape_job) * 1e3",
     "legendFormat": "{{agent_hostname}}: {{scrape_job}}"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_sd_discovered_targets{agent_hostname=\"$nodename\"})",
     "legendFormat": "Targets"
    }
   ]
  },
  { "title": "Prometheus Retrieval", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Average Scrape Interval Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_sum{agent_hostname=\"$nodename\"}[5m])\n/\nrate(prometheus_target_interval_length_seconds_count{agent_hostname=\"$nodename\"}[5m])\n* 1e3\n",
     "legendFormat": "{{agent_hostname}} {{interval}} configured"
    }
   ]
  },
  {
   "title": "Scrape failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(prometheus_target_scrapes_exceeded_sample_limit_total[1m]))",
     "legendFormat": "exceeded sample limit: {{job}}"
    },
    {
     "expr": "sum by (job) (rate(prometheus_target_scrapes_sample_duplicate_timestamp_total[1m]))",
     "legendFormat": "duplicate timestamp: {{job}}"
    },
    {
     "expr": "sum by (job) (rate(prometheus_target_scrapes_sample_out_of_bounds_total[1m]))",
     "legendFormat": "out of bounds: {{job}}"
    },
    {
     "expr": "sum by (job) (rate(prometheus_target_scrapes_sample_out_of_order_total[1m]))",
     "legendFormat": "out of order: {{job}}"
    }
   ]
  },
  {
   "title": "Appended Samples",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (agent_hostname, instance_group_name) (rate(agent_wal_storage_samples_appended_total{agent_hostname=\"$nodename\"}[5m]))",
     "legendFormat": "{{agent_hostname}} {{instance_name}}"
    }
   ]
  }
 ]
}