{
 "title": "Agent Operational",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Instance",
    "query": "label_values(agent_build_info, agent_hostname)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GCs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{agent_hostname=~\"$hostname\", job=\"integrations/agent\"}[5m])",
     "legendFormat": "{{agent_hostname}}"
    }
   ]
  },
  {
   "title": "Go Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{agent_hostname=~\"$hostname\", job=\"integrations/agent\"}",
     "legendFormat": "{{agent_hostname}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{agent_hostname=~\"$hostname\", job=\"integrations/agent\"}",
     "legendFormat": "{{agent_hostname}}"
    }
   ]
  },
  { "title": "Prometheus Read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Bytes/Series/Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(sum by (agent_hostname) (avg_over_time(go_memstats_heap_inuse_bytes{agent_hostname=~\"$hostname\", job=\"integrations/agent\"}[1m])))\n/\n(sum by (agent_hostname) (agent_wal_storage_active_series{agent_hostname=~\"$hostname\", job=\"integrations/agent\"}))\n",
     "legendFormat": "{{agent_hostname}}"
    }
   ]
  },
  {
   "title": "Bytes/Series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(sum (avg_over_time(go_memstats_heap_inuse_bytes{agent_hostname=~\"$hostname\", job=\"integrations/agent\"}[1m])))\n/\n(sum (agent_wal_storage_active_series{agent_hostname=~\"$hostname\", job=\"integrations/agent\"}))\n"
    }
   ]
  },
  {
   "title": "Series/Agent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (agent_hostname) (agent_wal_storage_active_series{agent_hostname=~\"$hostname\", job=\"integrations/agent\"})",
     "legendFormat": "{{agent_hostname}}"
    }
   ]
  },
  {
   "title": "Series/Config",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance_group_name) (agent_wal_storage_active_series{agent_hostname=~\"$hostname\", job=\"integrations/agent\"})",
     "legendFormat": "{{instance_group_name}}"
    }
   ]
  },
  {
   "title": "Series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (agent_hostname) (agent_wal_storage_active_series{agent_hostname=~\"$hostname\", job=\"integrations/agent\"})",
     "legendFormat": "{{agent_hostname}}"
    }
   ]
  }
 ]
}