{
 "title": "Node Exporter from Agent Integration",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{agent_hostname=~\"$hostname\",fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{agent_hostname=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{agent_hostname=~\"$hostname\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{agent_hostname=~\"$hostname\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{agent_hostname=~\"$hostname\"} / (node_memory_MemTotal_bytes{agent_hostname=~\"$hostname\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{agent_hostname=~\"$hostname\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {agent_hostname=~\"$hostname\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{agent_hostname=~\"$hostname\"} / node_memory_SwapTotal_bytes{agent_hostname=~\"$hostname\"})) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{agent_hostname=~\"$hostname\",mode=\"system\"}[30m])) by (agent_hostname)",
     "legendFormat": "{{agent_hostname}}_System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{agent_hostname=~\"$hostname\",mode=\"user\"}[30m])) by (agent_hostname)",
     "legendFormat": "{{agent_hostname}}_User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{agent_hostname=~\"$hostname\",mode=\"iowait\"}[30m])) by (agent_hostname)",
     "legendFormat": "{{agent_hostname}}_Iowait"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{agent_hostname=~\"$hostname\",mode=\"idle\"}[30m])) by (agent_hostname)",
     "legendFormat": "{{agent_hostname}}_Total"
    }
   ]
  },
  {
   "title": "Open  File Descriptor(left)/Context switches(right)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{agent_hostname=~\"$hostname\"}",
     "legendFormat": "filefd_{{agent_hostname}}"
    },
    {
     "expr": "irate(node_context_switches_total{agent_hostname=~\"$hostname\"}[30m])",
     "legendFormat": "switches_{{agent_hostname}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{agent_hostname=~\"$hostname\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU IOwait",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{agent_hostname=~\"$hostname\",mode=\"iowait\"}[30m])) * 100"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{agent_hostname=~\"$hostname\"}",
     "legendFormat": "{{agent_hostname}}_1m"
    },
    {
     "expr": "node_load5{agent_hostname=~\"$hostname\"}",
     "legendFormat": "{{agent_hostname}}_5m"
    },
    {
     "expr": "node_load15{agent_hostname=~\"$hostname\"}",
     "legendFormat": "{{agent_hostname}}_15m"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{agent_hostname=~\"$hostname\"}",
     "legendFormat": "{{agent_hostname}}_Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{agent_hostname=~\"$hostname\"} - node_memory_MemAvailable_bytes{agent_hostname=~\"$hostname\"}",
     "legendFormat": "{{agent_hostname}}_Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{agent_hostname=~\"$hostname\"}",
     "legendFormat": "{{agent_hostname}}_Avaliable"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{agent_hostname=~\"$hostname\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{agent_hostname}}_{{device}}_receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{agent_hostname=~\"$hostname\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{agent_hostname}}_{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "graph",
   "description": "Read/write completions per second",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{agent_hostname=~\"$hostname\"}[30m])",
     "legendFormat": "{{agent_hostname}}_{{device}}_Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{agent_hostname=~\"$hostname\"}[30m])",
     "legendFormat": "{{agent_hostname}}_{{device}}_Writes completed"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{agent_hostname=~\"$hostname\"}[30m])",
     "legendFormat": "{{agent_hostname}}_{{device}}_Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{agent_hostname=~\"$hostname\"}[30m])",
     "legendFormat": "{{agent_hostname}}_{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "graph",
   "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{agent_hostname=~\"$hostname\"}[30m])",
     "legendFormat": "{{agent_hostname}}_{{device}}_ IO time"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "graph",
   "description": "TCP_alloc - Allocated sockets\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nSockets_used - Sockets currently in use",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{agent_hostname=~\"$hostname\"}",
     "legendFormat": "{{agent_hostname}}_CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{agent_hostname=~\"$hostname\"}",
     "legendFormat": "{{agent_hostname}}_TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{agent_hostname=~\"$hostname\"}",
     "legendFormat": "{{agent_hostname}}_Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{agent_hostname=~\"$hostname\"}",
     "legendFormat": "{{agent_hostname}}_UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{agent_hostname=~\"$hostname\"}",
     "legendFormat": "{{agent_hostname}}_TCP_alloc"
    }
   ]
  },
  {
   "title": "Disk R/W Time(Reference: less than 100ms)(beta)",
   "type": "graph",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "s", "label": "Time. read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{agent_hostname=~\"$hostname\"}[30m]) / irate(node_disk_reads_completed_total{agent_hostname=~\"$hostname\"}[30m])",
     "legendFormat": "{{agent_hostname}}_{{device}}_Read time"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{agent_hostname=~\"$hostname\"}[30m]) / irate(node_disk_writes_completed_total{agent_hostname=~\"$hostname\"}[30m])",
     "legendFormat": "{{agent_hostname}}_{{device}}_Write time"
    }
   ]
  }
 ]
}