#
# Prerequisites: docker, docker-compose
#
- hosts: all
  become: true
  tasks:
  - name: Get bridge IP addresses
    become: false
    template:
      src: template/bridge_addrs.j2
      dest: ../machines.txt
    delegate_to: localhost
  - name: Install hosts file
    template:
      src: template/hosts.j2
      dest: /etc/hosts
  - name: Install apt-key
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      update_cache: yes
  - name: Add Docker repository key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Add Docker APT repository
    apt_repository:
      repo: 'deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable'
  - name: Install Docker Engine
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      update_cache: yes
  - name: Create docker group
    group:
      name: docker
  - name: Add vagrant to docker group
    user:
      name: vagrant
      append: yes
      groups: docker
  - name: Install prerequisites for docker-compose
    apt:
      name:
        - python3-pip
        - python3-setuptools
        - virtualenv
  - name: Install docker-compose
    pip:
      name: docker-compose
      executable: pip3

#
# Team role
#
- hosts: team
  tasks:
  - name: Load variables for templating
    include_vars:
      file: ../secrets.yaml
      name: secrets

  - name: Create directories for team docker-compose environment
    file:
      path: /home/vagrant/deploy/team/{{ item.path }}
      state: directory
      mode: "{{ item.mode }}"
    with_filetree: roles/team
    when: item.state == 'directory'

  - name: Copy team docker-compose environment
    template:
      src: "{{ item.src }}"
      dest: "/home/vagrant/deploy/team/{{ item.path }}"
    with_filetree: roles/team
    when: item.state == 'file'

  - name: Start team docker-compose environment
    docker_compose:
      project_src: /home/vagrant/deploy/team

#
# ETCD role
#
- hosts: etcd
  tasks:
  - name: Load variables for templating
    include_vars:
      file: ../secrets.yaml
      name: secrets

  - name: Create directories for etcd docker-compose environment
    file:
      path: /home/vagrant/deploy/etcd/{{ item.path }}
      state: directory
      mode: "{{ item.mode }}"
    with_filetree: roles/etcd
    when: item.state == 'directory'

  - name: Copy etcd docker-compose environment
    template:
      src: "{{ item.src }}"
      dest: "/home/vagrant/deploy/etcd/{{ item.path }}"
    with_filetree: roles/etcd
    when: item.state == 'file'

  - name: Start etcd docker-compose environment
    docker_compose:
      project_src: /home/vagrant/deploy/etcd

#
# Scraper role
#
- hosts: scraper
  tasks:
  - name: Load variables for templating
    include_vars:
      file: ../secrets.yaml
      name: secrets

  - name: Create directories for scraper docker-compose environment
    file:
      path: /home/vagrant/deploy/scraper/{{ item.path }}
      state: directory
      mode: "{{ item.mode }}"
    with_filetree: roles/scraper
    when: item.state == 'directory'

  - name: Copy scraper docker-compose environment
    template:
      src: "{{ item.src }}"
      dest: "/home/vagrant/deploy/scraper/{{ item.path }}"
    with_filetree: roles/scraper
    when: item.state == 'file'

  - name: Start scraper docker-compose environment
    docker_compose:
      project_src: /home/vagrant/deploy/scraper
